name: Assemble Modular Resumes

on:
  workflow_dispatch:  # Manual trigger

jobs:
  build-resumes:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        
      - name: Override remote with PAT
        env:
          TOKEN: ${{ secrets.GH_PAT }}
        run: git remote set-url origin https://x-access-token:${TOKEN}@github.com/BTExpress1/resume.git


      - name: Install Pandoc and LaTeX
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc texlive-xetex

      - name: Make script executable
        run: chmod +x assemble.sh

      - name: Run assembly script
        run: ./assemble.sh

      - name: Convert TPM resume to PDF
        run: pandoc TPM-AI-Compliance/resume.md -o TPM-AI-Compliance/resume.pdf

      - name: Convert DS resume to PDF
        run: pandoc Staff-Data-Scientist/resume.md -o Staff-Data-Scientist/resume.pdf
        
      - name: Convert TPM resume (no summary) to PDF
        run: pandoc TPM-AI-Compliance/resume-no-summary.md -o TPM-AI-Compliance/resume-no-summary.pdf

      - name: Convert DS resume (no summary) to PDF
        run: pandoc Staff-Data-Scientist/resume-no-summary.md -o Staff-Data-Scientist/resume-no-summary.pdf


      - name: Push changes
        run: |
          git config user.name "Bini Teklehaimanot"
          git config user.email "padgenb@gmail.com"
          git add TPM-AI-Compliance/resume.pdf TPM-AI-Compliance/resume-no-summary.pdf Staff-Data-Scientist/resume.pdf Staff-Data-Scientist/resume-no-summary.pdf
          git diff --cached --quiet || git commit -m "Rebuilt PDFs from existing Markdown"
          git push
