name: Convert Assembled Resumes to PDF

on:
  workflow_dispatch:

jobs:
  convert-pdfs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
    
      - name: Override remote with PAT
        env:
          TOKEN: ${{ secrets.GH_PAT }}
        run: git remote set-url origin https://x-access-token:${TOKEN}@github.com/BTExpress1/resume.git

      - name: Install Pandoc and LaTeX
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc texlive-xetex

      - name: Convert to PDF
        run: |
          pandoc TPM-AI-Compliance/resume.md -o TPM-AI-Compliance/resume.pdf
          pandoc Staff-Data-Scientist/resume.md -o Staff-Data-Scientist/resume.pdf
          pandoc TPM-AI-Compliance/resume-no-summary.md -o TPM-AI-Compliance/resume-no-summary.pdf
          pandoc Staff-Data-Scientist/resume-no-summary.md -o Staff-Data-Scientist/resume-no-summary.pdf

      - name: Push changes
        run: |
            git config user.name "Bini Teklehaimanot"
            git config user.email "padgenb@gmail.com"            
            git add TPM-AI-Compliance/resume.pdf TPM-AI-Compliance/resume-no-summary.pdf Staff-Data-Scientist/resume.pdf Staff-Data-Scientist/resume-no-summary.pdf
            git diff --cached --quiet || git commit -m "Rebuilt PDFs from existing Markdown"
            git push
